# Generated by Django 4.2.30 on 2026-08-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_advisorinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('program', models.CharField(max_length=120)),
                ('graduation_year', models.PositiveIntegerField()),
                ('company', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'placement_report_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
